### ISSUE TITLE
CUDA out of memory when change the form of building the network 

### ISSUE THREAD

**Issue by Iarkii** [junyanz/pytorch-CycleGAN-and-pix2pix#1053]
When I build the network the following way,  it shows CUDA out of memory.

```python

class ResnetGenerator(nn.Module):
    """Resnet-based generator that consists of Resnet blocks between a few downsampling/upsampling operations.

    We adapt Torch code and idea from Justin Johnson's neural style transfer project(https://github.com/jcjohnson/fast-neural-style)
    """

    def __init__(self, input_nc, output_nc, ngf=64, norm_layer=nn.BatchNorm2d, use_dropout=False, n_blocks=6, padding_type='reflect'):
        """Construct a Resnet-based generator

        Parameters:
            input_nc (int)      -- the number of channels in input images
            output_nc (int)     -- the number of channels in output images
            ngf (int)           -- the number of filters in the last conv layer
            norm_layer          -- normalization layer
            use_dropout (bool)  -- if use dropout layers
            n_blocks (int)      -- the number of ResNet blocks
            padding_type (str)  -- the name of padding layer in conv layers: reflect | replicate | zero
        """
        assert(n_blocks >= 0)
        super(ResnetGenerator, self).__init__()
        if type(norm_layer) == functools.partial:
            use_bias = norm_layer.func == nn.InstanceNorm2d
        else:
            use_bias = norm_layer == nn.InstanceNorm2d

        self.pad2d_0 = nn.ReflectionPad2d(3)
        self.conv_1 = nn.Conv2d(3, 64, kernel_size=(7, 7), stride=(1, 1), bias=False)
        self.batchnorm_2 = nn.BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.relu_3 = nn.ReLU(inplace=True)
        self.conv_4 = nn.Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        self.batchnorm_5 = nn.BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.conv_7 = nn.Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        self.batchnorm_8 = nn.BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.resbolck = ResnetBlock(ngf * 4, ngf * 4)
        self.upsamp_16 = nn.ConvTranspose2d(256, 128, kernel_size=(3, 3), stride=(2, 2),
                                     padding=(1, 1), output_padding=(1, 1), bias=False)
        self.upsamp_19 = nn.ConvTranspose2d(128, 64, kernel_size=(3, 3), stride=(2, 2),
                                      padding=(1, 1), output_padding=(1, 1), bias=False)
        self.conv_23 = nn.Conv2d(64, 3, kernel_size=(7, 7), stride=(1, 1))
        self.tanh = nn.Tanh()

    def forward(self, input):
        x = self.pad2d_0(input)
        x = self.conv_1(x)
        x = self.batchnorm_2(x)
        x = self.relu_3(x)
        x = self.conv_4(x)
        x = self.batchnorm_5(x)
        x = self.relu_3(x)  # (b, ngf, 256, 256)
        x = self.conv_7(x)
        x = self.batchnorm_8(x)
        x = self.relu_3(x)
        x = self.resbolck(x)  # (b, ngf*2, 64, 64)
        x = self.resbolck(x)
        x = self.resbolck(x)
        x = self.resbolck(x)
        x = self.resbolck(x)
        x = self.resbolck(x)
        x = self.upsamp_16(x)
        x = self.batchnorm_5(x)
        x = self.relu_3(x)
        x = self.upsamp_19(x)
        x = self.batchnorm_2(x)
        x = self.relu_3(x)
        x = self.pad2d_0(x)
        x = self.conv_23(x)
        x = self.tanh(x)
        return x
```

And I print the network, it has same size and structure with original network:   
```   
Total params: 7,841,411
Trainable params: 7,841,411
Non-trainable params: 0
    
Input size (MB): 0.75
Forward/backward pass size (MB): 686.09
Params size (MB): 29.91
Estimated Total Size (MB): 716.75
```
   
So what is the problem? Thanks for your reply.

**Comment by junyanz** [comment]
Not sure. Maybe you can print the shape of the tensor after each layer, and compare your implementation and ours.

**Comment by Iarkii** [comment]
Thanks a lot.I resolved it by using sequential model when building custom model.

**Comment by Iarkii** [comment]
> Not sure. Maybe you can print the shape of the tensor after each layer, and compare your implementation and ours.

Thanks for your reply. I resolved it by using sequential model when building custom model.
It seems like using sequential model can reducing memory usage.
