### ISSUE TITLE
CPU only 

### ISSUE THREAD

**Issue by jamesthesnake** [junyanz/pytorch-CycleGAN-and-pix2pix#11]
I went into the options folder and changed base_options  to 1 , but it is still looking for a nvidia chip I do not have.  Is it possible to run  cpu only?

**Comment by dribnet** [comment]
According to an [earlier issue](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/2#issuecomment-295029167), I think you might need the command line arg `--gpu_ids -1`.

**Comment by jamesthesnake** [comment]
I still get this error
`RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/autograd/engine.cpp:353
`

**Comment by jamesthesnake** [comment]
I thought it shouldn't matter for CPU only

**Comment by junyanz** [comment]
It works for me with CPU mode. This [issue](https://github.com/pytorch/pytorch/issues/1154) might be related.
