### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by nootfly** [junyanz/pytorch-CycleGAN-and-pix2pix#2]
When I trained a model, I got the below error. I'm using a Mac book pro. Thanks.
```
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 277, in __new__
    _lazy_init()
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 89, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 56, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by nootfly** [comment]
I added `--gpu_ids -1` and this issue was resolved. Thanks.

**Comment by pramodnitmz** [comment]
> I added `--gpu_ids -1` and this issue was resolved. Thanks.

where you added that

**Comment by ludwikbukowski** [comment]
have the same issue, where you added that ?

**Comment by junyanz** [comment]
You need to add it in the command line.

**Comment by rickkk856** [comment]
> I added `--gpu_ids -1` and this issue was resolved. Thanks.

I was having the same issue and found other people over the net having the same problem as well... 
This argument actually solve the problem to run the code on CPU, however I was going to test 80k files, so I needed it to run on my GPU... to do so, you need to install a torch version compatible with the CUDA version of your graphic card (see `!nvidia-smi`).

In my case the problem was installing the package using:
`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch` 
But when I ran `torch.cuda.is_available()` it returned `False` 

So to install the correct package instead of conda install, I used pip:
 `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
only then `torch.cuda.is_available()` returned `True` and I got it to work on `--gpu_ids 0`


PS: You can also check if your Torch Version has enabled CUDA just type:

```
import torch
print(torch.__version__)
```
`1.9.0+cu111` --> use `--gpu_ids 0`
`1.9.0+cpu` --> use `--gpu_ids -1`
