### ISSUE TITLE
Error in python: double free or corruption

### ISSUE THREAD

**Issue by alecalma** [junyanz/pytorch-CycleGAN-and-pix2pix#251]
I never had issues running train.py or test.py, and then randomly I got this error:

*** Error in `python': double free or corruption (!prev): 0x000056383cda7e40 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f18210217e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f182102a37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f182102e53c]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x2edd7c)[0x7f18074fdd7c]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x2eddc3)[0x7f18074fddc3]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x2ee064)[0x7f18074fe064]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x1e0930)[0x7f18073f0930]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x1baabc)[0x7f18073caabc]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(cuInit+0x4e)[0x7f180741956e]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(+0x1bdd5)[0x7f1803976dd5]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(+0x1be31)[0x7f1803976e31]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xea99)[0x7f1821382a99]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(+0x4e919)[0x7f18039a9919]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(+0x1800a)[0x7f180397300a]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(+0x1bceb)[0x7f1803976ceb]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/lib/libcudart-5d6d23a3.so.8.0.61(cudaSetDevice+0x47)[0x7f180399c1a7]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(_Z20THCPModule_setDevicei+0x9)[0x7f18048f48c9]
/home/alessandro/anaconda/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(_Z25THCPModule_setDevice_wrapP7_objectS0_+0x3a)[0x7f18048f491a]
python(_PyCFunction_FastCallDict+0x115)[0x56383a248f95]
python(+0x19cbec)[0x56383a2d6bec]
python(_PyEval_EvalFrameDefault+0x30a)[0x56383a2fb19a]
python(+0x1967db)[0x56383a2d07db]
python(+0x19ccc5)[0x56383a2d6cc5]
python(_PyEval_EvalFrameDefault+0x30a)[0x56383a2fb19a]
python(+0x1967db)[0x56383a2d07db]
python(+0x19ccc5)[0x56383a2d6cc5]
python(_PyEval_EvalFrameDefault+0x30a)[0x56383a2fb19a]
python(PyEval_EvalCodeEx+0x329)[0x56383a2d1529]
python(PyEval_EvalCode+0x1c)[0x56383a2d22cc]
python(+0x214af4)[0x56383a34eaf4]
python(PyRun_FileExFlags+0xa1)[0x56383a34eef1]
python(PyRun_SimpleFileExFlags+0x1c4)[0x56383a34f0f4]
python(Py_Main+0x648)[0x56383a352c28]
python(main+0xee)[0x56383a21a71e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f1820fca830]
python(+0x1c7c98)[0x56383a301c98]

Now I get it everytime I try to run again the code. Have you seen this before? Thank you!

**Comment by taesung89** [comment]
It looks like a cuda backend issue to me. I haven't had this problem. Have you tried reinstalling cuda and pytorch?

**Comment by junyanz** [comment]
Also,  what is your Pytorch version? The current code only works with PyTorch 0.1-0.3, not 0.4

**Comment by alecalma** [comment]
In the end I solved this by rebooting the machine.
