### ISSUE TITLE
cuda runtime error (30) : unknown error at torch/csrc/cuda/Module.cpp:32

### ISSUE THREAD

**Issue by xiaocaiyidiea** [junyanz/pytorch-CycleGAN-and-pix2pix#644]
hi I am student. I was successful when I ran this code last week. However, when I ran again today, there were some errors, and I was confused. Looking forward to your reply

File "/home/chy/pytorch-CycleGAN-and-pix2pix-master/train.py", line 28, in <module>
    opt = TrainOptions().parse()   # get training options
  File "/home/chy/pytorch-CycleGAN-and-pix2pix-master/options/base_options.py", line 135, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/home/chy/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 262, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (30) : unknown error at torch/csrc/cuda/Module.cpp:32

**Comment by xiaocaiyidiea** [comment]
my environment
- python=3.6
- pytorch=0.4.1

**Comment by xiaocaiyidiea** [comment]
The problem has been solved
